### ISSUE TITLE
Change project name from UI to GUI?

### ISSUE THREAD

**Issue by stevanlohja** [etclabscore/jade-desktop#70]
Can we rename the project from **UI** to **GUI**? User Interface is not defined enough. For example, a CLI is a command-line interface and GUI is a graphical user interface.

**Comment by shanejonas** [comment]
`jade-desktop` is what we are thinking about renaming this project to, see https://github.com/etclabscore/expedition/issues/175

**Comment by stevanlohja** [comment]
The project officially changed to Jade Desktop
